Adding CFLAGS to generator.lua
cimgui/cimgui pull request #165
Opened 2020-10-28 05:51 UTC by frink

This should solve the problems of #164 as well as a host of other possibilities.

Basically this adds the ability to add CFLAGS to the command line of `generator.lua` as long as they start with a dash. (Note this only works with `gcc` and `clang` since `cl` doesn't allow you to get `#defines`) We could add the slash for completeness, but the only place this is useful is inside the `get_defines()` function which clearly states that `cl` is incapable of supporting the call.

2020-10-28 05:55 UTC, frink commented
Before merging we should probably add something to the documentation. But I'm not sure where that would be best put. Suggestions? Comments?

2020-10-28 08:43 UTC, sonoro1234 commented
> Before merging we should probably add something to the documentation. But I'm not sure where that would be best put.

https://github.com/cimgui/cimgui#using-generator

if you modify imconfig.h and generate, compilation wont need anything else, if you use the CFLAGS in the generator you must also use them in the compilation. I dont know what is cleaner.

2020-10-28 15:25 UTC, frink commented
> if you modify imconfig.h and generate, compilation wont need anything else, if you use the CFLAGS in the generator you must also use them in the compilation. I dont know what is cleaner.

This is mostly about code management. It depends entirely on the build tooling and repo management as to which approach is cleaner. Both have merit in different contexts. In my case, I'm trying to avoid maintaining forks of repositories with modifications. I'm in the early stages and I already have five submodules in my app template. In these cases it makes sense to pass around `-DIMGUI_USER_CONFIG="\"myconfig.h\""` rather than modifing imconfig.h in a submodule referencing a fork that you have to maintain. (Remember submodules do not allow local modifications...) But if someone is greatly modifying Dear ImGui for their own uses then a forked repo makes sense to keep things kosher. 

Like I said: both have merit depending on context...

2020-10-28 16:40 UTC, sonoro1234 commented
Please add the documentation in readme and generator.bat (sh)

2020-10-29 15:25 UTC, sonoro1234 reviewed
...

2020-10-29 15:27 UTC, sonoro1234 requested changes
Please add documentation to readme and generator.bat (sh)

2020-10-29 16:33 UTC, frink commented
Okay, I've added documentation in README.md, generator.bat and generator.lua.

2020-10-29 17:15 UTC, sonoro1234 commented on README.md
ofthe -> of the

2020-10-29 17:16 UTC, sonoro1234 commented on generator/generator.bat
>  luajit ./generator.lua gcc "internal" glfw opengl3 opengl2 sdl
CLFLAGS -> CFLAGS

2020-10-29 17:16 UTC, sonoro1234 commented on generator/generator.sh
>  luajit ./generator.lua gcc "internal" glfw opengl3 opengl2 sdl
CLFLAGS

2020-10-29 17:17 UTC, sonoro1234 requested changes
ofthe -> of the 
CLFAGS

2020-10-29 17:29 UTC, frink commented
Lesson learned. Don't do PRs while playing LEGO with your kids...

2020-10-29 19:36 UTC, sonoro1234 approved these changes

2020-10-29 19:37 UTC, merged

2020-10-29 19:37 UTC, sonoro1234 commented
Thanks!!

2020-10-29 22:00 UTC, frink commented
Thank you for merging!